name: my-workflow  # Name of your workflow

on:  # Triggers the workflow
  push:  # On pushes to branches
    branches: [ master ] 
  pull_request:  # On pull requests
    branches: [ master ]
  # workflow_dispatch:
jobs:
  build:  # Name of the job

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '11.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
