name: workflow-dev

on:
  push:
    branches:
      - tuantv
  pull_request:
    branches:
      - tuantv

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: echo Hello  # Replace with your specific test command

      - name: Set environment variables
        run: chmod +x ./.github/workflows/env.sh && ./.github/workflows/env.sh
        env:
          ApiKey: ${{secrets.AZURE_APIKEY}}
        shell: bash

      - name: Display Updated appsettings.json
        run: cat ./appsettings.json
